### ISSUE TITLE
circuit diagram

### ISSUE THREAD

**Issue by gahbes** [sqwk/arduino-latency-test#1]
Would you mind sharing a circuit diagram for this?

**Comment by sqwk** [comment]
Unfortunately, I don't have the board in question connected any longer. However, there is really only two pins that you'll need to connect: pin 2 for the LED and pin A0 for the LDR and these pins can be changed in code. Depending on your LED and LDR you'll need to stick a resistor in there as well; which one will depend on your LED and LDR. Google "LDR Arduino" or "LED Arduino" and you'll find plenty of hookup guides. This really just combines the two.

If you want to use a display, hook that up to the two I2C pins. Otherwise just comment out the display lines. Examples are also available in the repo for the Adafruit_SSD1306 library.

**Comment by gahbes** [comment]
Thank you for getting back to me. I got it to work in the end.

I wasn't quite sure where to get the threshold value from but it seems to
work fine with your default.

Many thanks,
Seb
